dist: bionic

language: node_js

node_js:
- 12

before_script:
  - 'which ssh-agent || (sudo apt-get update -y && sudo apt-get install openssh-client git zip -y)'
  - eval $(ssh-agent -s)
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

install:
  - npm i -g gitbook-cli

jobs:
  include:
    - stage: build
      name: "Build docker"
      script:
        - cd docker/en && gitbook build
    - stage: deploy
      name: "Deploy docker"
      script:
        - cd docker/en
        - gitbook build
        - zip -r docker-en.zip _book
        - scp docker-en.zip $TARGET_SERVER:/var/www/html/workshop.threeengineers.id
        - ssh $TARGET_SERVER "cd /var/www/html/workshop.threeengineers.id && unzip docker-en.zip"