dist: bionic

language: node_js

node_js:
- 12

before_script:
  - 'which ssh-agent || (sudo apt-get update -y && sudo apt-get install openssh-client git zip -y)'
  - eval $(ssh-agent -s)
  - ssh-add <(echo $SSH_PRIVATE_KEY | base64 -d)
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

install:
  - npm i -g gitbook-cli

jobs:
  include:
    - stage: build
      name: "Build docker for EN"
      script:
        - cd docker/en && gitbook build
    - stage: build
      name: "Build docker for ID"
      script:
        - cd docker/id && gitbook build
    - stage: deploy
      name: "Deploy docker material for EN"
      env:
        - LANG=en
        - TARGET_FOLDER="/var/www/html/workshop.threeengineers.id/docker"
      script:
        - cd docker/$LANG && gitbook build
        - mv _book $LANG
        - zip -r $LANG.zip $LANG
        - scp $LANG.zip $TARGET_SERVER:$TARGET_FOLDER
        - ssh $TARGET_SERVER "cd $TARGET_FOLDER && unzip $LANG.zip && rm -rf $LANG.zip"
    - stage: deploy
      name: "Deploy docker material for ID"
      env:
        - LANG=id
        - TARGET_FOLDER="/var/www/html/workshop.threeengineers.id/docker"
      script:
        - cd docker/$LANG && gitbook build
        - mv _book $LANG
        - zip -r $LANG.zip $LANG
        - scp $LANG.zip $TARGET_SERVER:$TARGET_FOLDER
        - ssh $TARGET_SERVER "cd $TARGET_FOLDER && unzip $LANG.zip && rm -rf $LANG.zip"
    - stage: deploy
      name: "Clean zip"
      script:
        - ssh $TARGET_SERVER "cd $TARGET_FOLDER && rm -rf *.zip"